apiVersion: v1
kind: Service
metadata: 
    name: {{ .Values.postgres.name }}
spec:
    selector:
        app: {{ .Values.postgres.name }}
    ports:
      - name: {{ .Values.postgres.name }}-listener
        protocol: TCP
        port: {{ .Values.postgres.port }}
        targetPort: {{ .Values.postgres.name }}
