apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
    app: gateway
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
