version: 13.8
port: 5432

default_database:
  name: postgres
  user: postgres
  password: postgres

users:
  - name: program
    password: test

datases:
  - name: tickets
    user: program
  - name: flights
    user: program
  - name: privileges
    user: program

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi