flight:
  service:
    type: NodePort
    port: 8070
    nodePort: 30070
    image: jokerva1010123/flight-service:latest
    env:
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres

bonus:
  service:
    type: NodePort
    port: 8060
    nodePort: 30060
    image: jokerva1010123/bonus-service:latest
    env:
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres

ticket:
  service:
    type: NodePort
    port: 8050
    nodePort: 30050
    image: jokerva1010123/ticket-service:latest
    env:
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres

gateway:
   service:
    type: NodePort
    port: 8080
    nodePort: 30000
    image: jokerva1010123/gateway:latest
    isGateway: true
    env:
      FLIGHT_SERVICE_HOST: flight.jokerva1010123.svc.cluster.local
      FLIGHT_SERVICE_PORT: 8070
      BONUS_SERVICE_HOST: bonus.jokerva1010123.svc.cluster.local
      BONUS_SERVICE_PORT: 8060
      TICKET_SERVICE_HOST: ticket.jokerva1010123.svc.cluster.local
      TICKET_SERVICE_PORT: 8050