bonus:
  port: 8050
  image:
    repository: vuquang142k/rsoi-lab4:bonus
    tag: 1.0
  database:
    name: privileges
    username: program
    password: test

flight:
  port: 8060
  image:
    repository: vuquang142k/rsoi-lab4:flight
    tag: 1.0
  database:
    name: flights
    username: program
    password: test

ticket:
  port: 8070
  image:
    repository: vuquang142k/rsoi-lab4:ticket
    tag: 1.0
  database:
    name: tickets
    username: program
    password: test

gateway:
  port: 8080
  image:
    repository: vuquang142k/rsoi-lab4:gateway
    tag: 1.0
  isGateway: true