name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

      - name: Login in dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build docker images
        run: |
          docker build ./src/bonus-service/ -t vuquang142k/rsoi-lab4:bonus
          docker build ./src/flight-service/ -t vuquang142k/rsoi-lab4:flight
          docker build ./src/gateway-service/ -t vuquang142k/rsoi-lab4:gateway
          docker build ./src/ticket-service/ -t vuquang142k/rsoi-lab4:ticket

      - name: Push docker images
        run: |
          docker push vuquang142k/rsoi-lab4:bonus
          docker push vuquang142k/rsoi-lab4:flight
          docker push vuquang142k/rsoi-lab4:ticket
          docker push vuquang142k/rsoi-lab4:gateway

      - name: Kubectl
        uses: Azure/setup-kubectl@v3.1

      - name: Create kube config
        run: |
          mkdir $HOME/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > $HOME/.kube/config

      - name: Deploy Helm
        run: |
          helm install services k8s/services-chart
          sleep 30